# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-spring-app:latest .

      - name: Run container
        run: |
          docker stop my-spring-app
          docker rm my-spring-app
          docker run -d `
            --name my-spring-app `
            --restart unless-stopped `
            -p ${{secrets.SERVER_PORT}}:8080 `
            my-spring-app:latest